### ISSUE TITLE
Set this project to global standards

### ISSUE THREAD

**Issue by arpit1997** [ITCoders/SyncIt#3]
Make a new src  folder and put all codes in that folder. Make it pep8 compliant

**Comment by 24paras** [comment]
Hi! I would like to take this issue.

**Comment by arpit1997** [comment]
Go for it. @24paras

**Comment by 24paras** [comment]
@arpit1997  Thanks! I started with the drive_sync.py file and I have removed most of the violations.
I'm just left with the ones which says "E501 line too long (more than 79 characters)."
 Would like to know that if your code has this line :- 
foldered_list = drive.ListFile({'q':  "'"+parent_directory_id+ "' ' in parents and trashed=false"}).GetList()  
Can I shorten it this way ?
x = parent_directory_id 
message = " ' in parents and trashed=false"
 foldered_list = drive.ListFile({'q':  "'"+x+ message}).GetList()  
Thanks !

**Comment by arpit1997** [comment]
yeah sure why not. But make sure you run the code once to avoid any syntax errors.

**Comment by 24paras** [comment]
Sure, will do so!
